# Generated by Django 2.1.4 on 2020-04-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mst_Award_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Award_category_code', models.IntegerField(verbose_name='受賞コード')),
                ('Award_category_kanji', models.CharField(max_length=10, verbose_name='受賞名漢字')),
                ('Award_category_kana', models.CharField(max_length=20, verbose_name='受賞名かな')),
                ('Award_category_name1', models.CharField(blank=True, max_length=10, verbose_name='名称１')),
                ('Award_category_name2', models.CharField(blank=True, max_length=10, verbose_name='名称２')),
                ('Award_category_name3', models.CharField(blank=True, max_length=10, verbose_name='名称３')),
            ],
            options={
                'verbose_name_plural': '受賞区分マスタ',
            },
        ),
        migrations.CreateModel(
            name='Mst_Basho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basho_code', models.IntegerField(verbose_name='場所コード')),
                ('Basho_kanji', models.CharField(max_length=10, verbose_name='場所名漢字')),
                ('Basho_kana', models.CharField(max_length=20, verbose_name='場所名かな')),
                ('Basho_month', models.IntegerField(verbose_name='月')),
                ('Basho_1char', models.CharField(blank=True, max_length=2, verbose_name='１文字略称')),
                ('Basho_symbol', models.CharField(blank=True, max_length=2, verbose_name='１文字記号')),
                ('Weight_measure_category', models.IntegerField(blank=True, null=True, verbose_name='体重測定区分')),
            ],
            options={
                'verbose_name_plural': '場所マスタ',
            },
        ),
        migrations.CreateModel(
            name='Mst_Chii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chii_code', models.IntegerField(verbose_name='地位コード')),
                ('Chii_kanji', models.CharField(max_length=10, verbose_name='地位名漢字')),
                ('Chii_kana', models.CharField(max_length=20, verbose_name='地位名かな')),
                ('Chii_2char', models.CharField(max_length=4, verbose_name='２文字略称')),
                ('Chii_3char', models.CharField(max_length=6, verbose_name='３文字名称')),
                ('Chii_name1', models.CharField(blank=True, max_length=20, verbose_name='名称１')),
                ('Chii_name2', models.CharField(blank=True, max_length=20, verbose_name='名称２')),
                ('Chii_name3', models.CharField(blank=True, max_length=20, verbose_name='名称３')),
                ('Sort_code', models.IntegerField(blank=True, null=True, verbose_name='ソートコード')),
            ],
            options={
                'verbose_name_plural': '地位マスタ',
            },
        ),
        migrations.CreateModel(
            name='Mst_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_code', models.IntegerField(verbose_name='階級コード')),
                ('Class_name_kanji', models.CharField(max_length=10, verbose_name='階級名漢字')),
                ('Class_name_kana', models.CharField(max_length=20, verbose_name='階級名かな')),
                ('Class_name_1char', models.CharField(max_length=2, verbose_name='１文字略称')),
                ('Class_name_3char', models.CharField(max_length=6, verbose_name='３文字名称')),
                ('Banzuke_1char', models.CharField(max_length=2, verbose_name='階級番付１文字略称')),
                ('Class_name1', models.CharField(blank=True, max_length=20, verbose_name='名称１')),
                ('Class_name2', models.CharField(blank=True, max_length=20, verbose_name='名称２')),
                ('Class_name3', models.CharField(blank=True, max_length=20, verbose_name='名称３')),
            ],
            options={
                'verbose_name_plural': '階級マスタ',
            },
        ),
        migrations.CreateModel(
            name='Mst_Eastwest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eastwest_code', models.IntegerField(verbose_name='東西コード')),
                ('Eastwest_name', models.CharField(max_length=2, verbose_name='東西名称')),
            ],
            options={
                'verbose_name_plural': '東西マスタ',
            },
        ),
        migrations.CreateModel(
            name='Mst_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_date', models.IntegerField(verbose_name='開催年月')),
                ('Frist_date', models.DateField(verbose_name='初日年月日')),
                ('Banzuke_date', models.DateField(verbose_name='番付発表日')),
                ('Age_calcu_reference_date', models.DateField(verbose_name='年齢算出基準日')),
                ('Basho_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Basho')),
            ],
            options={
                'verbose_name_plural': '（システム状態に移行したので削除）開催マスタ',
            },
        ),
        migrations.CreateModel(
            name='Mst_Gameinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_category', models.IntegerField(verbose_name='勝負区分')),
                ('Game_mark', models.CharField(blank=True, max_length=2, verbose_name='勝負マーク')),
                ('Game_mark2', models.CharField(blank=True, max_length=2, verbose_name='勝負マーク２')),
                ('Cumulative_class', models.IntegerField(blank=True, null=True, verbose_name='累積区分')),
                ('Participation_division', models.IntegerField(blank=True, null=True, verbose_name='出場区分')),
                ('Opponent_category', models.IntegerField(blank=True, null=True, verbose_name='相手勝負区分')),
                ('Screendisplay_category', models.IntegerField(blank=True, null=True, verbose_name='画面表示区分')),
                ('Screendisplay_string', models.CharField(blank=True, max_length=40, verbose_name='画面表示文字列')),
                ('Name1', models.CharField(blank=True, max_length=20, verbose_name='名称１')),
                ('Name2', models.CharField(blank=True, max_length=20, verbose_name='名称２')),
                ('Name3', models.CharField(blank=True, max_length=20, verbose_name='名称３')),
            ],
            options={
                'verbose_name_plural': '勝負情報',
            },
        ),
        migrations.CreateModel(
            name='Mst_Heya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heya_code', models.IntegerField(verbose_name='部屋コード')),
                ('Heya_official_kanji', models.CharField(max_length=10, verbose_name='正式名称漢字')),
                ('Heya_official_kana', models.CharField(max_length=20, verbose_name='正式名称かな')),
                ('Heya_kanji_2char', models.CharField(max_length=4, verbose_name='２文字部屋名漢字')),
                ('Heya_kanji_3char', models.CharField(max_length=6, verbose_name='３文字部屋名漢字')),
                ('Heya_kanji_2char_jikai', models.CharField(blank=True, max_length=8, verbose_name='２文字部屋名字解コード配列')),
                ('Heya_kanji_3char_jikai', models.CharField(blank=True, max_length=12, verbose_name='３文字部屋名字解コード配列')),
            ],
            options={
                'verbose_name_plural': '部屋マスタ',
            },
        ),
        migrations.CreateModel(
            name='Mst_Hometown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hometown_code', models.IntegerField(verbose_name='出身地コード')),
                ('Country_prefecture_kanji', models.CharField(max_length=20, verbose_name='国・都道府県名漢字')),
                ('Country_prefecture_kana', models.CharField(max_length=40, verbose_name='国・都道府県名かな')),
                ('Country_prefecture_2char', models.CharField(max_length=4, verbose_name='２文字略称')),
                ('Country_prefecture_3char', models.CharField(max_length=6, verbose_name='３文字略称')),
            ],
            options={
                'verbose_name_plural': '出身地マスタ',
            },
        ),
        migrations.CreateModel(
            name='Mst_Kimarite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heya_code', models.IntegerField(verbose_name='決まり手コード')),
                ('Kimarite_name', models.CharField(max_length=32, verbose_name='決まり手名称')),
                ('Kimarite_abbr_5char', models.CharField(max_length=10, verbose_name='決まり手５文字略称')),
                ('Display_order', models.IntegerField(verbose_name='表示順')),
                ('Opponent_kimarite_code', models.IntegerField(verbose_name='相手決まり手コード')),
            ],
            options={
                'verbose_name_plural': '決まり手マスタ',
            },
        ),
        migrations.CreateModel(
            name='Mst_KindofNewsML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content_code', models.IntegerField(blank=True, null=True, verbose_name='電文種別コード')),
                ('ContentName', models.CharField(blank=True, max_length=32, null=True, verbose_name='電文種別名称')),
                ('Group_code', models.IntegerField(blank=True, null=True, verbose_name='グループＩＤ')),
                ('NewsMLNo', models.CharField(blank=True, max_length=4, null=True, verbose_name='NewsML種別コード')),
            ],
            options={
                'verbose_name_plural': '電文種別',
            },
        ),
        migrations.CreateModel(
            name='Mst_Lifetime_award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numberofaward', models.IntegerField(verbose_name='受賞回数')),
                ('Award_category_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Award_category')),
            ],
            options={
                'verbose_name_plural': '生涯受賞回数マスタ',
            },
        ),
        migrations.CreateModel(
            name='Mst_Lifetime_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Totalbasho', models.IntegerField(verbose_name='通算出場場所回数')),
                ('Totalwins', models.IntegerField(verbose_name='通算勝ち回数')),
                ('Totalloss', models.IntegerField(verbose_name='通算負け回数')),
                ('Totalkyuujou', models.IntegerField(verbose_name='通算休場回数')),
                ('Totalties', models.IntegerField(verbose_name='通算分け回数')),
                ('Totalgivekinboshi', models.IntegerField(verbose_name='通算与金星回数')),
                ('Totalgetkinboshi', models.IntegerField(verbose_name='通算奪金星回数')),
                ('Highestorder', models.IntegerField(verbose_name='最高順位')),
                ('Maxsticking', models.IntegerField(verbose_name='最高張付')),
                ('Overallwinrate', models.IntegerField(verbose_name='通算勝率')),
                ('Overallwinrate_yasumimake', models.IntegerField(verbose_name='通算勝率（休を負）')),
                ('Maxcontinuousplayed', models.IntegerField(verbose_name='最高連続出場回数')),
                ('Currentcontinuosplayed', models.IntegerField(verbose_name='現連続出場回数')),
                ('Numberofreignedbasho', models.IntegerField(verbose_name='在位場所数')),
                ('Class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Class')),
                ('Highestchii_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Chii')),
            ],
            options={
                'verbose_name_plural': '生涯成績マスタ',
            },
        ),
        migrations.CreateModel(
            name='Mst_Lifetime_statusinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chii_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Chii')),
            ],
            options={
                'verbose_name_plural': '生涯地位情報',
            },
        ),
        migrations.CreateModel(
            name='Mst_Nichime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nichime_code', models.IntegerField(verbose_name='日目コード')),
                ('Nichime_name', models.CharField(max_length=6, verbose_name='日目名称')),
                ('Nichime_3char', models.CharField(blank=True, max_length=10, verbose_name='３文字略称')),
                ('Nichime_4char', models.CharField(blank=True, max_length=10, verbose_name='４文字略称')),
                ('Touzai_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Eastwest')),
            ],
            options={
                'verbose_name_plural': '日目マスタ',
            },
        ),
        migrations.CreateModel(
            name='Mst_Operationmode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operationmode_code', models.IntegerField(blank=True, null=True, verbose_name='運用モード')),
                ('Operationmode_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='運用モード表記')),
            ],
            options={
                'verbose_name_plural': '運用管理',
            },
        ),
        migrations.CreateModel(
            name='Mst_Rikishi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rikishi_code', models.IntegerField(verbose_name='力士コード')),
                ('Rikishi_name_kanji_official', models.CharField(blank=True, max_length=10, verbose_name='正式力士名漢字')),
                ('Rikishi_name_kanji_kana', models.CharField(blank=True, max_length=20, verbose_name='正式力士名かな')),
                ('Rikishi_name_Kanji_2char', models.CharField(blank=True, max_length=4, verbose_name='２文字力士名漢字')),
                ('Rikishi_name_Kanji_3char', models.CharField(blank=True, max_length=6, verbose_name='３文字力士名漢字')),
                ('Rikishi_name_Kanji_4char', models.CharField(blank=True, max_length=8, verbose_name='４文字力士名漢字')),
                ('Rikishi_name_jikai_code_official', models.CharField(blank=True, max_length=20, verbose_name='正式力士名字解コード配列')),
                ('Rikishi_name_jikai_code_2char', models.CharField(blank=True, max_length=8, verbose_name='２文字力士名字解コード配列')),
                ('Rikishi_name_jikai_code_3char', models.CharField(blank=True, max_length=12, verbose_name='３文字力士名字解コード配列')),
                ('Rikishi_name_jikai_code_4char', models.CharField(blank=True, max_length=16, verbose_name='４文字力士名字解コード配列')),
                ('OCR_rikishi_name_Kanji', models.CharField(blank=True, max_length=10, verbose_name='OCR用力士名漢字')),
                ('Real_name', models.CharField(blank=True, max_length=20, verbose_name='本名')),
                ('Date_of_birth', models.DateField(blank=True, verbose_name='生年月日西暦')),
                ('Hometown_details_1', models.CharField(blank=True, max_length=64, verbose_name='出身地詳細１')),
                ('Hometown_details_abbr1_2char', models.CharField(blank=True, max_length=4, verbose_name='出身地詳細２文字略称１')),
                ('Hometown_details_abbr1_3char', models.CharField(blank=True, max_length=6, verbose_name='出身地詳細３文字略称１')),
                ('Hometown_details_2', models.CharField(blank=True, max_length=64, verbose_name='出身地詳細２')),
                ('Hometown_details_abbr2_2char', models.CharField(blank=True, max_length=4, verbose_name='出身地詳細２文字略称２')),
                ('Hometown_details_abbr2_3char', models.CharField(blank=True, max_length=6, verbose_name='出身地詳細３文字略称２')),
                ('Alien_classification', models.BooleanField(verbose_name='外国人区分')),
                ('Height', models.IntegerField(blank=True, null=True, verbose_name='身長')),
                ('Weight', models.IntegerField(blank=True, null=True, verbose_name='体重')),
                ('Last_weight', models.IntegerField(blank=True, null=True, verbose_name='前回体重')),
                ('Hatsudohyou_year', models.IntegerField(blank=True, null=True, verbose_name='初土俵年')),
                ('Tukedashi_class', models.BooleanField(verbose_name='付出区分')),
                ('Tukedashi_maime', models.IntegerField(blank=True, null=True, verbose_name='付出枚目')),
                ('Retired_year_AD', models.IntegerField(blank=True, null=True, verbose_name='引退年月西暦')),
                ('Hometown_details_Municipality_1', models.CharField(blank=True, max_length=66, verbose_name='出身地詳細市町村１')),
                ('Hometown_details_Municipality_2', models.CharField(blank=True, max_length=66, verbose_name='出身地詳細市町村２')),
                ('Day_of_retirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Nichime')),
                ('Hatsubasho_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hatsubasyo', to='app_sumo.Mst_Basho')),
                ('Heya_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Heya')),
                ('Hometown_code_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hometown1', to='app_sumo.Mst_Hometown')),
                ('Hometown_code_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hometown2', to='app_sumo.Mst_Hometown')),
                ('Retirebasho_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retirement', to='app_sumo.Mst_Basho')),
            ],
            options={
                'verbose_name_plural': '力士マスタ',
            },
        ),
        migrations.CreateModel(
            name='Mst_Rikishistatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rikishistatus_code', models.IntegerField(verbose_name='状態コード')),
                ('Rikishistatus_name', models.CharField(max_length=5, verbose_name='状態名称')),
            ],
            options={
                'verbose_name_plural': '力士状態マスタ',
            },
        ),
        migrations.CreateModel(
            name='Tran_Banzuke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Join_code', models.IntegerField(blank=True, null=True, verbose_name='参加区分')),
                ('Banzuke_rank', models.IntegerField(blank=True, null=True, verbose_name='番付順位')),
                ('Haridashi', models.IntegerField(blank=True, null=True, verbose_name='張付区分')),
                ('Banzuke_no', models.IntegerField(blank=True, null=True, verbose_name='番付通番')),
                ('Appear_code', models.IntegerField(blank=True, null=True, verbose_name='新再降区分')),
                ('Demoted_rank', models.IntegerField(blank=True, null=True, verbose_name='昇降順位')),
                ('Chii_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Chii')),
                ('Class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Class')),
                ('Eastwest_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Eastwest')),
            ],
            options={
                'verbose_name_plural': '*番付明細\u3000NewsML作成（01:新番付資料）',
            },
        ),
        migrations.CreateModel(
            name='Tran_Systemstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_date', models.IntegerField(blank=True, null=True, verbose_name='開催年月')),
                ('First_date', models.DateField(verbose_name='初日年月日')),
                ('Banzuke_date', models.DateField(verbose_name='番付発表日')),
                ('Age_calcu_reference_date', models.DateField(verbose_name='年齢算出基準日')),
                ('CurrentBasho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Basho')),
                ('MatchDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='app_sumo.Mst_Nichime')),
                ('SystemStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Operationmode')),
                ('TorikumiDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torikumi', to='app_sumo.Mst_Nichime')),
            ],
            options={
                'verbose_name_plural': '#システム状態',
            },
        ),
        migrations.CreateModel(
            name='Tran_TopClassRikishi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yearmonth', models.DateField(verbose_name='開催年月西暦')),
                ('LossCount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='負け数')),
                ('WinCount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='勝ち数')),
                ('Class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Class', verbose_name='階級')),
                ('Nichime_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Nichime', verbose_name='日目')),
            ],
            options={
                'verbose_name_plural': '*階級上位力士',
            },
        ),
        migrations.AddField(
            model_name='tran_banzuke',
            name='Event_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Tran_Systemstatus'),
        ),
        migrations.AddField(
            model_name='tran_banzuke',
            name='RikishiId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Rikishi'),
        ),
        migrations.AddField(
            model_name='mst_rikishi',
            name='Rikishi_attrib_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Rikishistatus'),
        ),
        migrations.AddField(
            model_name='mst_rikishi',
            name='Tukedashi_class_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Class'),
        ),
        migrations.AddField(
            model_name='mst_lifetime_statusinfo',
            name='Rikishi_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Rikishi'),
        ),
        migrations.AddField(
            model_name='mst_lifetime_result',
            name='Rikishi_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Rikishi'),
        ),
        migrations.AddField(
            model_name='mst_lifetime_result',
            name='Touzai_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Eastwest'),
        ),
        migrations.AddField(
            model_name='mst_lifetime_award',
            name='Rikishi_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Rikishi'),
        ),
        migrations.AddField(
            model_name='mst_gameinfo',
            name='Kimarite_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Kimarite'),
        ),
        migrations.AddField(
            model_name='mst_event',
            name='Shoubu_nichime_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoubu_nichime', to='app_sumo.Mst_Nichime'),
        ),
        migrations.AddField(
            model_name='mst_event',
            name='Torikumi_nichime_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torikumi_nichime', to='app_sumo.Mst_Nichime'),
        ),
    ]
