# Generated by Django 2.2.6 on 2019-11-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_name_formal',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
