# Generated by Django 2.2.6 on 2019-11-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0003_auto_20191103_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='waza',
            name='waza_name_formal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='waza',
            name='waza_name_formal3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
