# Generated by Django 2.2.6 on 2019-11-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0004_auto_20191103_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waza',
            old_name='waza_name_formal3',
            new_name='waza_name_formal7',
        ),
    ]
