# Generated by Django 2.1.4 on 2020-03-28 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0004_auto_20200328_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mst_Lifetime_award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numberofaward', models.IntegerField(verbose_name='受賞回数')),
                ('Award_category_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Award_category')),
                ('Rikishi_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Rikishi')),
            ],
            options={
                'verbose_name_plural': '生涯受賞回数マスタ',
            },
        ),
    ]
