# Generated by Django 2.1.4 on 2020-03-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0005_mst_lifetime_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='NML_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryNo', models.IntegerField(blank=True, null=True, verbose_name='登録順位')),
                ('BashoCount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Lifetime_result')),
                ('Event_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Tran_Systemstatus')),
                ('RikishiId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Nichime')),
            ],
            options={
                'verbose_name_plural': '*NewsML 01：新番付資料',
            },
        ),
    ]
