# Generated by Django 2.1.4 on 2020-03-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0006_nml_01'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nml_01',
            name='BashoCount',
        ),
        migrations.RemoveField(
            model_name='nml_01',
            name='Event_date',
        ),
        migrations.RemoveField(
            model_name='nml_01',
            name='RikishiId',
        ),
        migrations.RemoveField(
            model_name='tran_systemstatus',
            name='CurrentBasho',
        ),
        migrations.RemoveField(
            model_name='tran_systemstatus',
            name='MatchDate',
        ),
        migrations.RemoveField(
            model_name='tran_systemstatus',
            name='SystemStatus',
        ),
        migrations.RemoveField(
            model_name='tran_systemstatus',
            name='TorikumiDate',
        ),
        migrations.AlterModelOptions(
            name='mst_event',
            options={'verbose_name_plural': '（システム状態に移行したので削除）開催マスタ'},
        ),
        migrations.DeleteModel(
            name='NML_01',
        ),
        migrations.DeleteModel(
            name='Tran_Systemstatus',
        ),
    ]
