# Generated by Django 2.2.6 on 2019-11-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0006_playerresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerResult',
        ),
    ]
