# Generated by Django 2.2.6 on 2019-11-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0008_auto_20191103_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player1winloss',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2winloss',
        ),
    ]
