# Generated by Django 2.1.4 on 2020-03-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0008_auto_20200328_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nml_01',
            name='BashoCount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Nichime'),
        ),
        migrations.AlterField(
            model_name='nml_01',
            name='RikishiId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Lifetime_result'),
        ),
    ]
