# Generated by Django 2.2.7 on 2019-11-15 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0010_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1absence',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1loss',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1tie',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1win',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2absence',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2loss',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2tie',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2win',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='match',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
