# Generated by Django 2.1.4 on 2020-03-29 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0012_nml_00_comm_incontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nml_00_comm_incontent',
            name='Competition',
        ),
        migrations.RemoveField(
            model_name='nml_00_comm_incontent',
            name='CompetitionDay',
        ),
        migrations.RemoveField(
            model_name='nml_00_comm_incontent',
            name='YearMonth',
        ),
        migrations.DeleteModel(
            name='NML_00_comm_incontent',
        ),
    ]
