# Generated by Django 2.1.4 on 2020-03-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0012_auto_20200214_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mst_Lifetime_statusinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rikishi_code', models.IntegerField(verbose_name='力士コード')),
                ('Chii_code', models.IntegerField(verbose_name='地位コード')),
            ],
            options={
                'verbose_name_plural': '生涯地位情報',
            },
        ),
    ]
