# Generated by Django 2.1.4 on 2020-03-29 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0013_auto_20200329_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tran_Banzuke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banzuke_rank', models.IntegerField(blank=True, null=True, verbose_name='番付順位')),
                ('Haridashi', models.IntegerField(blank=True, null=True, verbose_name='張付区分')),
                ('Banzuke_no', models.IntegerField(blank=True, null=True, verbose_name='番付通番')),
                ('Demoted_rank', models.IntegerField(blank=True, null=True, verbose_name='昇降順位')),
                ('Chii_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Chii')),
                ('Class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Class')),
                ('Eastwest_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Eastwest')),
                ('Event_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Tran_Systemstatus')),
                ('RikishiId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Tran_Banzuke')),
            ],
            options={
                'verbose_name_plural': '*番付明細\u3000NewsML作成（01:新番付資料）',
            },
        ),
        migrations.RemoveField(
            model_name='nml_01',
            name='BashoCount',
        ),
        migrations.RemoveField(
            model_name='nml_01',
            name='Event_date',
        ),
        migrations.RemoveField(
            model_name='nml_01',
            name='RikishiId',
        ),
        migrations.DeleteModel(
            name='NML_01',
        ),
    ]
