# Generated by Django 2.1.4 on 2020-03-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0014_mst_lifetime_award'),
        ('app_sumo', '0013_mst_lifetime_statusinfo'),
    ]

    operations = [
    ]
