# Generated by Django 2.1.4 on 2020-03-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0014_auto_20200329_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='tran_banzuke',
            name='Join_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='参加区分'),
        ),
    ]
