# Generated by Django 2.1.4 on 2020-03-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0015_tran_banzuke_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tran_banzuke',
            name='Appear_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='新・再・降区分'),
        ),
    ]
