# Generated by Django 2.1.4 on 2020-03-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0016_mst_gameinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mst_gameinfo',
            name='Kimarite_code',
        ),
        migrations.RemoveField(
            model_name='mst_lifetime_award',
            name='Award_category_code',
        ),
        migrations.RemoveField(
            model_name='mst_lifetime_result',
            name='Class_code',
        ),
        migrations.RemoveField(
            model_name='mst_lifetime_result',
            name='Highestchii_code',
        ),
        migrations.RemoveField(
            model_name='mst_lifetime_result',
            name='Rikishi_code',
        ),
        migrations.RemoveField(
            model_name='mst_lifetime_result',
            name='Touzai_division',
        ),
        migrations.DeleteModel(
            name='Mst_Lifetime_statusinfo',
        ),
        migrations.DeleteModel(
            name='Mst_Gameinfo',
        ),
        migrations.DeleteModel(
            name='Mst_Lifetime_award',
        ),
        migrations.DeleteModel(
            name='Mst_Lifetime_result',
        ),
    ]
