# Generated by Django 2.1.4 on 2020-03-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0016_tran_banzuke_appear_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tran_banzuke',
            name='Appear_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='新再降区分'),
        ),
    ]
