# Generated by Django 2.1.4 on 2020-03-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0017_auto_20200329_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tran_banzuke',
            name='RikishiId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Rikishi'),
        ),
    ]
