# Generated by Django 2.1.4 on 2020-03-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0018_mst_gameinfo_mst_lifetime_award_mst_lifetime_result_mst_lifetime_statusinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mst_gameinfo',
            name='Cumulative_class',
            field=models.IntegerField(blank=True, null=True, verbose_name='累積区分'),
        ),
        migrations.AlterField(
            model_name='mst_gameinfo',
            name='Game_mark',
            field=models.CharField(blank=True, max_length=2, verbose_name='勝負マーク'),
        ),
        migrations.AlterField(
            model_name='mst_gameinfo',
            name='Game_mark2',
            field=models.CharField(blank=True, max_length=2, verbose_name='勝負マーク２'),
        ),
        migrations.AlterField(
            model_name='mst_gameinfo',
            name='Opponent_category',
            field=models.IntegerField(blank=True, null=True, verbose_name='相手勝負区分'),
        ),
        migrations.AlterField(
            model_name='mst_gameinfo',
            name='Participation_division',
            field=models.IntegerField(blank=True, null=True, verbose_name='出場区分'),
        ),
        migrations.AlterField(
            model_name='mst_gameinfo',
            name='Screendisplay_category',
            field=models.IntegerField(blank=True, null=True, verbose_name='画面表示区分'),
        ),
        migrations.AlterField(
            model_name='mst_gameinfo',
            name='Screendisplay_string',
            field=models.CharField(blank=True, max_length=40, verbose_name='画面表示文字列'),
        ),
    ]
