# Generated by Django 2.1.4 on 2020-04-01 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0019_auto_20200331_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mst_basho',
            name='Bashi_1char',
        ),
        migrations.RemoveField(
            model_name='mst_basho',
            name='Bashi_kana',
        ),
    ]
