# Generated by Django 2.1.4 on 2020-03-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0015_merge_20200310_1858'),
        ('app_sumo', '0019_auto_20200310_1837'),
    ]

    operations = [
    ]
