# Generated by Django 2.1.4 on 2020-04-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0020_auto_20200401_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='mst_basho',
            name='Basho_1char',
            field=models.CharField(blank=True, max_length=2, verbose_name='１文字略称'),
        ),
        migrations.AddField(
            model_name='mst_basho',
            name='Basho_kana',
            field=models.CharField(default=1, max_length=20, verbose_name='場所名かな'),
            preserve_default=False,
        ),
    ]
