# Generated by Django 2.1.4 on 2020-03-13 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0020_merge_20200312_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventinfo',
        ),
        migrations.RemoveField(
            model_name='match',
            name='outcome1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='outcome2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='waza',
        ),
        migrations.DeleteModel(
            name='Memo',
        ),
        migrations.DeleteModel(
            name='PostCsv',
        ),
        migrations.AlterField(
            model_name='mst_lifetime_statusinfo',
            name='Chii_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Chii'),
        ),
        migrations.AlterField(
            model_name='mst_lifetime_statusinfo',
            name='Rikishi_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Rikishi'),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Waza',
        ),
    ]
