# Generated by Django 2.1.4 on 2020-03-23 02:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0021_auto_20200313_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taikai_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1win', models.IntegerField(blank=True, default='0')),
                ('player1loss', models.IntegerField(blank=True, default='0')),
                ('player1tie', models.IntegerField(blank=True, default='0')),
                ('player1absence', models.IntegerField(blank=True, default='0')),
                ('player2win', models.IntegerField(blank=True, default='0')),
                ('player2loss', models.IntegerField(blank=True, default='0')),
                ('player2absence', models.IntegerField(blank=True, default='0')),
                ('player2tie', models.IntegerField(blank=True, default='0')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mst_KindofNewsML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content_code', models.IntegerField(blank=True, null=True, verbose_name='電文種別コード')),
                ('ContentName', models.CharField(blank=True, max_length=32, null=True, verbose_name='電文種別名称')),
                ('Group_code', models.IntegerField(blank=True, null=True, verbose_name='グループＩＤ')),
                ('NewsMLNo', models.CharField(blank=True, max_length=2, null=True, verbose_name='NewsML種別コード')),
            ],
            options={
                'verbose_name_plural': '電文種別',
            },
        ),
        migrations.CreateModel(
            name='Mst_Operationmode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operationmode_code', models.IntegerField(blank=True, null=True, verbose_name='運用モード')),
                ('Operationmode_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='運用モード表記')),
            ],
            options={
                'verbose_name_plural': '運用管理',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=200)),
                ('winloss', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
                ('player_name_formal', models.CharField(blank=True, max_length=200)),
                ('player_name_formal3', models.CharField(blank=True, max_length=200)),
                ('player_name_yomi', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Tran_Systemstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentBasho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Basho')),
                ('MatchDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='app_sumo.Mst_Nichime')),
                ('SystemStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Operationmode')),
                ('TorikumiDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torikumi', to='app_sumo.Mst_Nichime')),
            ],
            options={
                'verbose_name_plural': '#システム状態',
            },
        ),
        migrations.CreateModel(
            name='Waza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waza_name', models.CharField(max_length=200)),
                ('waza_name_formal', models.CharField(blank=True, max_length=200)),
                ('waza_name_formal7', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='mst_chii',
            name='Sort_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='ソートコード'),
        ),
        migrations.AddField(
            model_name='match',
            name='outcome1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rikishi_1', to='app_sumo.Outcome'),
        ),
        migrations.AddField(
            model_name='match',
            name='outcome2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rikishi_2', to='app_sumo.Outcome'),
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rikishi_1', to='app_sumo.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rikishi_2', to='app_sumo.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='waza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Waza'),
        ),
    ]
