# Generated by Django 2.1.4 on 2020-03-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0021_auto_20200313_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mst_gameinfo',
            name='Kimarite_code',
        ),
        migrations.DeleteModel(
            name='Mst_Gameinfo',
        ),
    ]
