# Generated by Django 2.1.4 on 2020-04-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0021_auto_20200401_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mst_nichime',
            old_name='Nicime_3char',
            new_name='Nichime_3char',
        ),
        migrations.RenameField(
            model_name='mst_nichime',
            old_name='Nicime_4char',
            new_name='Nichime_4char',
        ),
        migrations.RenameField(
            model_name='mst_nichime',
            old_name='Nicime_code',
            new_name='Nichime_code',
        ),
        migrations.RenameField(
            model_name='mst_nichime',
            old_name='Nicime_name',
            new_name='Nichime_name',
        ),
    ]
