# Generated by Django 2.1.4 on 2020-03-20 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0022_auto_20200320_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mst_Gameinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_category', models.IntegerField(verbose_name='勝負区分')),
                ('Game_mark', models.CharField(blank=True, max_length=2, verbose_name='勝負マーク')),
                ('Game_mark2', models.CharField(blank=True, max_length=2, verbose_name='勝負マーク２')),
                ('Cumulative_class', models.IntegerField(blank=True, null=True, verbose_name='累積区分')),
                ('Participation_division', models.IntegerField(blank=True, null=True, verbose_name='出場区分')),
                ('Opponent_category', models.IntegerField(blank=True, null=True, verbose_name='相手勝負区分')),
                ('Screendisplay_category', models.IntegerField(blank=True, null=True, verbose_name='画面表示区分')),
                ('Screendisplay_string', models.CharField(blank=True, max_length=40, verbose_name='画面表示文字列')),
                ('Name1', models.CharField(blank=True, max_length=20, verbose_name='名称１')),
                ('Name2', models.CharField(blank=True, max_length=20, verbose_name='名称２')),
                ('Name3', models.CharField(blank=True, max_length=20, verbose_name='名称３')),
                ('Kimarite_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Kimarite')),
            ],
            options={
                'verbose_name_plural': '勝負情報',
            },
        ),
    ]
