# Generated by Django 2.1.4 on 2020-04-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0022_auto_20200401_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mst_lifetime_result',
            name='Totalgetkinboshi',
            field=models.IntegerField(verbose_name='通算奪金星回数'),
        ),
        migrations.AlterField(
            model_name='mst_lifetime_result',
            name='Totalgivekinboshi',
            field=models.IntegerField(verbose_name='通算与金星回数'),
        ),
    ]
