# Generated by Django 2.1.4 on 2020-04-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0023_auto_20200401_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tran_systemstatus',
            old_name='Frist_date',
            new_name='First_date',
        ),
    ]
