# Generated by Django 2.1.4 on 2020-03-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0024_mst_kindofnewsml'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mst_KindofNewsML',
        ),
    ]
