# Generated by Django 2.1.4 on 2020-03-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0025_delete_mst_kindofnewsml'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mst_KindofNewsML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContentName', models.CharField(blank=True, max_length=32, null=True, verbose_name='電文種別名称')),
                ('Group_code', models.IntegerField(blank=True, null=True, verbose_name='グループＩＤ')),
                ('NewsMLNo', models.IntegerField(blank=True, null=True, verbose_name='NewsML種別コード')),
            ],
            options={
                'verbose_name_plural': '電文種別',
            },
        ),
    ]
