# Generated by Django 2.1.4 on 2020-03-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0027_auto_20200320_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='mst_chii',
            name='Sort_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='ソートコード'),
        ),
    ]
