# Generated by Django 2.1.4 on 2020-03-23 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0028_mst_chii_sort_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mst_Operationmode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operationmode_code', models.IntegerField(blank=True, null=True, verbose_name='運用モード')),
                ('Operationmode_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='運用モード表記')),
            ],
            options={
                'verbose_name_plural': '運用管理',
            },
        ),
        migrations.CreateModel(
            name='Tran_Systemstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentBasho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Basho')),
                ('MatchDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='app_sumo.Mst_Nichime')),
                ('SystemStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sumo.Mst_Operationmode')),
                ('TorikumiDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torikumi', to='app_sumo.Mst_Nichime')),
            ],
            options={
                'verbose_name_plural': '#システム状態',
            },
        ),
    ]
