# Generated by Django 2.1.4 on 2020-03-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0029_mst_operationmode_tran_systemstatus'),
        ('app_sumo', '0022_auto_20200323_1143'),
    ]

    operations = [
    ]
