# Generated by Django 2.1.4 on 2020-03-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0030_merge_20200323_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventinfo',
            options={'verbose_name_plural': 'イベント'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': '試合'},
        ),
        migrations.AlterModelOptions(
            name='outcome',
            options={'verbose_name_plural': '勝負'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name_plural': '選手'},
        ),
        migrations.AlterModelOptions(
            name='waza',
            options={'verbose_name_plural': '技'},
        ),
    ]
