# Generated by Django 2.1.4 on 2020-03-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0031_auto_20200323_1802'),
        ('app_sumo', '0030_merge_20200323_1711'),
    ]

    operations = [
    ]
