# Generated by Django 2.1.4 on 2020-03-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumo', '0032_merge_20200325_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventinfo',
        ),
        migrations.RemoveField(
            model_name='match',
            name='outcome1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='outcome2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='waza',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Waza',
        ),
    ]
