# Generated by Django 2.1.4 on 2020-03-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_autorace', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auto_schedule',
        ),
        migrations.DeleteModel(
            name='csvtest1',
        ),
        migrations.DeleteModel(
            name='systemstatus',
        ),
    ]
