# Generated by Django 2.2.7 on 2020-02-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autorace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tran_schedule',
            name='Raceplace1',
            field=models.CharField(blank=True, max_length=1, verbose_name='場コード1'),
        ),
        migrations.AddField(
            model_name='tran_schedule',
            name='Raceplace2',
            field=models.CharField(blank=True, max_length=1, verbose_name='場コード2'),
        ),
        migrations.AddField(
            model_name='tran_schedule',
            name='Raceplace3',
            field=models.CharField(blank=True, max_length=1, verbose_name='場コード3'),
        ),
        migrations.AddField(
            model_name='tran_schedule',
            name='Raceplace4',
            field=models.CharField(blank=True, max_length=1, verbose_name='場コード4'),
        ),
        migrations.AddField(
            model_name='tran_schedule',
            name='Raceplace5',
            field=models.CharField(blank=True, max_length=1, verbose_name='場コード5'),
        ),
        migrations.AddField(
            model_name='tran_schedule',
            name='Raceplace6',
            field=models.CharField(blank=True, max_length=1, verbose_name='場コード6'),
        ),
        migrations.AddField(
            model_name='tran_schedule',
            name='Totalracenum1',
            field=models.CharField(blank=True, max_length=2, verbose_name='レース数1'),
        ),
        migrations.AddField(
            model_name='tran_schedule',
            name='Totalracenum2',
            field=models.CharField(blank=True, max_length=2, verbose_name='レース数2'),
        ),
        migrations.AddField(
            model_name='tran_schedule',
            name='Totalracenum3',
            field=models.CharField(blank=True, max_length=2, verbose_name='レース数3'),
        ),
        migrations.AddField(
            model_name='tran_schedule',
            name='Totalracenum4',
            field=models.CharField(blank=True, max_length=2, verbose_name='レース数4'),
        ),
        migrations.AddField(
            model_name='tran_schedule',
            name='Totalracenum5',
            field=models.CharField(blank=True, max_length=2, verbose_name='レース数5'),
        ),
        migrations.AddField(
            model_name='tran_schedule',
            name='Totalracenum6',
            field=models.CharField(blank=True, max_length=2, verbose_name='レース数6'),
        ),
        migrations.AlterField(
            model_name='tran_schedule',
            name='DateOfRace1',
            field=models.CharField(blank=True, max_length=8, verbose_name='競走年月日1'),
        ),
        migrations.AlterField(
            model_name='tran_schedule',
            name='DateOfRace2',
            field=models.CharField(blank=True, max_length=8, verbose_name='競走年月日2'),
        ),
        migrations.AlterField(
            model_name='tran_schedule',
            name='DateOfRace3',
            field=models.CharField(blank=True, max_length=8, verbose_name='競走年月日3'),
        ),
        migrations.AlterField(
            model_name='tran_schedule',
            name='SalesInfo1',
            field=models.CharField(blank=True, max_length=1, verbose_name='場外発売情報1'),
        ),
        migrations.AlterField(
            model_name='tran_schedule',
            name='SalesInfo2',
            field=models.CharField(blank=True, max_length=1, verbose_name='場外発売情報2'),
        ),
        migrations.AlterField(
            model_name='tran_schedule',
            name='SalesInfo3',
            field=models.CharField(blank=True, max_length=1, verbose_name='場外発売情報3'),
        ),
    ]
