# Generated by Django 2.2.7 on 2020-02-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autorace', '0002_auto_20200201_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='役職名')),
            ],
        ),
    ]
