# Generated by Django 2.2.7 on 2020-02-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autorace', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='社長', max_length=50, verbose_name='役職名'),
        ),
    ]
