# Generated by Django 2.2.7 on 2020-02-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_autorace', '0004_auto_20200204_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
