# Generated by Django 2.1.4 on 2020-04-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tran_Systemstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unyou_date', models.DateField(verbose_name='運用日')),
            ],
            options={
                'verbose_name_plural': '#システム状態',
            },
        ),
    ]
