# Generated by Django 2.1.4 on 2020-04-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ckeiba', '0002_auto_20200402_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mst_Honjitu_Shikou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Honjitu_Shikou_date', models.DateField(verbose_name='本日施行情報')),
            ],
            options={
                'verbose_name_plural': '【スケジュール系】本日施行情報',
            },
        ),
        migrations.CreateModel(
            name='Mst_Kaisai_Hiwari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kaisai_Hiwari_date', models.DateField(verbose_name='開催日割')),
            ],
            options={
                'verbose_name_plural': '【スケジュール系】開催日割',
            },
        ),
        migrations.AlterField(
            model_name='mst_breed_age',
            name='Breed_age_age_name',
            field=models.CharField(max_length=10, verbose_name='馬齢条件用名称'),
        ),
        migrations.AlterField(
            model_name='mst_breed_age',
            name='Breed_age_breed_name',
            field=models.CharField(max_length=10, verbose_name='品種年齢名称'),
        ),
        migrations.AlterField(
            model_name='mst_breed_age',
            name='Breed_age_name',
            field=models.CharField(max_length=10, verbose_name='競走種別用名称'),
        ),
        migrations.AlterField(
            model_name='mst_grade',
            name='Grade_name',
            field=models.CharField(max_length=5, verbose_name='グレード名称'),
        ),
        migrations.AlterField(
            model_name='mst_jou',
            name='Jou_1corner',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='１コーナー名称'),
        ),
        migrations.AlterField(
            model_name='mst_jou',
            name='Jou_2corner',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='２コーナー名称'),
        ),
        migrations.AlterField(
            model_name='mst_jou',
            name='Jou_3corner',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='３コーナー名称'),
        ),
        migrations.AlterField(
            model_name='mst_jou',
            name='Jou_4corner',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='４コーナー名称'),
        ),
        migrations.AlterField(
            model_name='mst_night_race',
            name='Night_race_code',
            field=models.BooleanField(verbose_name='ナイター区分コード'),
        ),
        migrations.AlterField(
            model_name='mst_night_race',
            name='Night_race_name',
            field=models.CharField(max_length=5, verbose_name='ナイター区分名称'),
        ),
    ]
