# Generated by Django 2.1.4 on 2020-04-06 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ckeiba', '0004_tran_systemstatus_systemstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mst_operationmode',
            name='Operationmode_code',
            field=models.IntegerField(verbose_name='運用モード'),
        ),
        migrations.AlterField(
            model_name='mst_operationmode',
            name='Operationmode_name',
            field=models.CharField(max_length=15, verbose_name='運用モード表記'),
        ),
        migrations.AlterField(
            model_name='tran_systemstatus',
            name='SystemStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_ckeiba.Mst_Operationmode'),
        ),
    ]
