# Generated by Django 2.1.4 on 2020-04-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ckeiba', '0005_auto_20200406_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mst_haishin',
            name='Jou_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ckeiba.Mst_Jou', verbose_name='競馬場コード'),
        ),
        migrations.AlterField(
            model_name='mst_haishin_gentei',
            name='Company_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ckeiba.Mst_Company', verbose_name='配信社コード'),
        ),
        migrations.AlterField(
            model_name='mst_haishin_gentei',
            name='Jou_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ckeiba.Mst_Jou', verbose_name='競馬場コード'),
        ),
    ]
